name: Webseite verschlüsseln und hochladen

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: StatiCrypt ausführen
        uses: jirutka/setup-staticrypt-action@v1
        with:
          password: ${{ secrets.STATICRYPT_PASSWORD }}
          title: "Geschützter Bereich"
          instructions: "Bitte gib dein Passwort ein."
          output: "index.html"

      - name: GitHub Pages konfigurieren
        uses: actions/configure-pages@v5

      - name: Dateien verpacken
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Direkt zu GitHub Pages hochladen
        uses: actions/deploy-pages@v4
